package main;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
    @Autowired // This means to get the bean called customerRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private CustomerRepository customerRepository;

    @RequestMapping("/")
    public String index() {
        return "Greetings from Spring Boot!";
    }

    @GetMapping(path="/add") // Map ONLY GET Requests
    public @ResponseBody String addNewUser (@RequestParam String firstName
            , @RequestParam String lastName) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Customer n = new Customer();
        n.setFirstName(firstName);
        n.setLastName(lastName);
        customerRepository.save(n);
        return "Saved";
    }

    @GetMapping(path="/findbylastname")
    public @ResponseBody Iterable<Customer> findByLastName (@RequestParam String lastName) {
        return customerRepository.findByLastName(lastName);
    }

    @GetMapping(path="/findbyid")
    public @ResponseBody Customer findById (@RequestParam Long id) {
        return customerRepository.findById(id)
                .get();
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Customer> getAllUsers() {
        // This returns a JSON or XML with the users
        return customerRepository.findAll();
    }
}